// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2kJvHYxyN0XIXLlcq1WiUy-cs0EqB4lE',
    appId: '1:593702848172:web:de3a199bf285723861c109',
    messagingSenderId: '593702848172',
    projectId: 'findify-b8687',
    authDomain: 'findify-b8687.firebaseapp.com',
    storageBucket: 'findify-b8687.appspot.com',
    measurementId: 'G-6KPJXT3LCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvdlSH0wrnGBaflA2OQXTvCqLiN1nRsLY',
    appId: '1:593702848172:android:da110104ec3c35e061c109',
    messagingSenderId: '593702848172',
    projectId: 'findify-b8687',
    storageBucket: 'findify-b8687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_5kzmYju0z5GMFJomrpU4N3MbnEByfCk',
    appId: '1:593702848172:ios:c69b0e47ac70eb1261c109',
    messagingSenderId: '593702848172',
    projectId: 'findify-b8687',
    storageBucket: 'findify-b8687.appspot.com',
    iosBundleId: 'com.example.businessinfoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_5kzmYju0z5GMFJomrpU4N3MbnEByfCk',
    appId: '1:593702848172:ios:c69b0e47ac70eb1261c109',
    messagingSenderId: '593702848172',
    projectId: 'findify-b8687',
    storageBucket: 'findify-b8687.appspot.com',
    iosBundleId: 'com.example.businessinfoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2kJvHYxyN0XIXLlcq1WiUy-cs0EqB4lE',
    appId: '1:593702848172:web:101899f0b173acac61c109',
    messagingSenderId: '593702848172',
    projectId: 'findify-b8687',
    authDomain: 'findify-b8687.firebaseapp.com',
    storageBucket: 'findify-b8687.appspot.com',
    measurementId: 'G-V66F9HXE3D',
  );
}
